# Site settings
title: katecpp
email: kasia.macias@gmail.com
description: "Blog about software development, C++ and Qt."
baseurl: ""
url: "http://katecpp.github.io"
production_url: "http://katecpp.github.io"
twitter_username: katie_cpp
github_username:  katecpp

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 15
