# Site settings
title: katecpp
email: kasia.macias@gmail.com
description: ""
baseurl: ""
url: "http://katecpp.github.io"
twitter_username: katie_cpp
github_username:  katecpp

# Build settings
markdown: kramdown
permalink: pretty
